
//dummy.dart
import 'package:electric_battery_delivery_frontend/components/models.dart';

class DummyData {
  static final User dummyUser = User(
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phoneNumber: '+91 9876543210',
    address: 'HSR Layout, Bangalore',
    gender: 'Male',
    vehicles: ['Ola Electric', 'Ather 450X'],
    preferences: {
      'preferred_location': 'Koramangala',
      'notification': true,
      'language': 'English',
    },
  );

  static final List<Order> orders = [
    Order(
      id: '1',
      type: 'station',
      locationName: 'Koramangala Station',
      date: '2025-02-22',
      status: 'Completed',
      amount: 299.99,
      details: {
        'battery_capacity': '5kWh',
        'duration': '30 mins',
        'payment_method': 'UPI',
      },
    ),
  ];

  static final List<Building> buildings = [
    Building(
      id: '1',
      name: 'Tech Park One',
      address: 'Whitefield Main Road',
      totalSlots: 20,
      availableSlots: 15,
      distance: 2.5,
      status: 'Open',
      price: 399.99,
      amenities: ['Parking', 'Security', '24/7 Access'],
      imageUrl: 'assets/images/building1.jpg',
      features: {
        'charging_speed': 'Fast',
        'security': 'CCTV Monitored',
        'access_type': 'Card Based',
      },
    ),
  ];

  static final List<Station> stations = [
    Station(
      id: 1,
      name: "Bangalore Central Station",
      address: "123 Main St, Bangalore",
      managerName: "John Doe",
      email: "stationa@example.com",
      phone: "9876543210",
      latitude: 12.9716,
      longitude: 77.5946,
      isActive: true,
      createdAt: "2025-03-26T05:11:04.414Z",
      updatedAt: "2025-03-26T05:11:04.414Z",
      status: "Available",
      etaMinutes: 5,
      availableBatteries: 15,
      price: 1200,
      imageUrl: "https://example.com/station_a.jpg",
      batteryCapacity: "48 kWh",
      availableBatteryTypes: [
        Battery(
          id: 1,
          type: "Lithium-Ion 48V Standard",
          description: "Standard capacity battery for everyday use",
          price: 1000,
          availableQuantity: 8,
          voltage: 48.0,
          capacity: 20.0,
          imageUrl: "https://example.com/battery1.jpg",
        ),
        Battery(
          id: 2,
          type: "Lithium-Ion 48V Extended",
          description: "Extended capacity for longer range",
          price: 1500,
          availableQuantity: 5,
          voltage: 48.0,
          capacity: 30.0,
          imageUrl: "https://example.com/battery2.jpg",
        ),
        Battery(
          id: 3,
          type: "LFP 48V High Performance",
          description: "High performance battery with fast charging",
          price: 2000,
          availableQuantity: 2,
          voltage: 48.0,
          capacity: 25.0,
          imageUrl: "https://example.com/battery3.jpg",
        ),
      ],
    ),
    
    // Nasik Station
    Station(
      id: 2,
      name: "Nasik EV Hub",
      address: "45 College Road, Nasik",
      managerName: "Priya Sharma",
      email: "nasikstation@example.com",
      phone: "8765432109",
      latitude: 19.9975,
      longitude: 73.7898,
      isActive: true,
      createdAt: "2025-03-25T08:15:04.414Z",
      updatedAt: "2025-03-26T06:22:14.414Z",
      status: "Available",
      etaMinutes: 8,
      availableBatteries: 12,
      price: 1100,
      imageUrl: "https://example.com/nasik_station.jpg",
      batteryCapacity: "52 kWh",
      availableBatteryTypes: [
        Battery(
          id: 4,
          type: "Lithium-Ion 52V Standard",
          description: "Standard capacity battery for everyday use",
          price: 1050,
          availableQuantity: 6,
          voltage: 52.0,
          capacity: 22.0,
          imageUrl: "https://example.com/battery4.jpg",
        ),
        Battery(
          id: 5,
          type: "Lithium-Ion 52V Extended",
          description: "Extended capacity for longer range",
          price: 1600,
          availableQuantity: 4,
          voltage: 52.0,
          capacity: 32.0,
          imageUrl: "https://example.com/battery5.jpg",
        ),
        Battery(
          id: 6,
          type: "LFP 52V High Performance",
          description: "High performance battery with fast charging",
          price: 2100,
          availableQuantity: 2,
          voltage: 52.0,
          capacity: 28.0,
          imageUrl: "https://example.com/battery6.jpg",
        ),
      ],
    ),
    
    // Rushi Station
    Station(
      id: 3,
      name: "Rushi Power Station",
      address: "78 Tech Park, Mumbai",
      managerName: "Rushi Patel",
      email: "rushipower@example.com",
      phone: "7654321098",
      latitude: 19.0760,
      longitude: 72.8777,
      isActive: true,
      createdAt: "2025-03-24T12:30:04.414Z",
      updatedAt: "2025-03-26T07:45:14.414Z",
      status: "Busy",
      etaMinutes: 15,
      availableBatteries: 8,
      price: 1300,
      imageUrl: "https://example.com/rushi_station.jpg",
      batteryCapacity: "60 kWh",
      availableBatteryTypes: [
        Battery(
          id: 7,
          type: "Lithium-Ion 60V Performance",
          description: "High performance battery for power users",
          price: 1400,
          availableQuantity: 3,
          voltage: 60.0,
          capacity: 25.0,
          imageUrl: "https://example.com/battery7.jpg",
        ),
        Battery(
          id: 8,
          type: "Lithium-Ion 60V Extended Range",
          description: "Maximum range for long distance travel",
          price: 1800,
          availableQuantity: 3,
          voltage: 60.0,
          capacity: 35.0,
          imageUrl: "https://example.com/battery8.jpg",
        ),
        Battery(
          id: 9,
          type: "LFP 60V Premium",
          description: "Premium battery with advanced features",
          price: 2300,
          availableQuantity: 2,
          voltage: 60.0,
          capacity: 30.0,
          imageUrl: "https://example.com/battery9.jpg",
        ),
      ],
    ),
    
    // Additional station for diversity
    Station(
      id: 4,
      name: "Koramangala Exchange",
      address: "34 Inner Ring Road, Bangalore",
      managerName: "Vikram Singh",
      email: "koramangala@example.com",
      phone: "9654321087",
      latitude: 12.9352,
      longitude: 77.6245,
      isActive: true,
      createdAt: "2025-03-23T10:45:04.414Z",
      updatedAt: "2025-03-26T08:30:14.414Z",
      status: "Available",
      etaMinutes: 3,
      availableBatteries: 20,
      price: 1250,
      imageUrl: "https://example.com/koramangala_station.jpg",
      batteryCapacity: "48 kWh",
      availableBatteryTypes: [
        Battery(
          id: 10,
          type: "Lithium-Ion 48V Economy",
          description: "Budget-friendly battery with good performance",
          price: 950,
          availableQuantity: 10,
          voltage: 48.0,
          capacity: 18.0,
          imageUrl: "https://example.com/battery10.jpg",
        ),
        Battery(
          id: 11,
          type: "Lithium-Ion 48V Standard Plus",
          description: "Enhanced standard battery with faster charging",
          price: 1150,
          availableQuantity: 7,
          voltage: 48.0,
          capacity: 22.0,
          imageUrl: "https://example.com/battery11.jpg",
        ),
        Battery(
          id: 12,
          type: "LFP 48V Premium",
          description: "Premium battery with longer lifecycle",
          price: 1750,
          availableQuantity: 3,
          voltage: 48.0,
          capacity: 24.0,
          imageUrl: "https://example.com/battery12.jpg",
        ),
      ],
    ),
    
    // One more station with Maintenance status
    Station(
      id: 5,
      name: "HSR Layout Hub",
      address: "56 Sector 2, HSR Layout, Bangalore",
      managerName: "Ananya Desai",
      email: "hsrlayout@example.com",
      phone: "8543210976",
      latitude: 12.9116,
      longitude: 77.6741,
      isActive: false,
      createdAt: "2025-03-22T09:30:04.414Z",
      updatedAt: "2025-03-26T04:15:14.414Z",
      status: "Maintenance",
      etaMinutes: 0,
      availableBatteries: 0,
      price: 1200,
      imageUrl: "https://example.com/hsr_station.jpg",
      batteryCapacity: "50 kWh",
      availableBatteryTypes: [],
    ),
  ];
}